INSERT INTO HR.DEPARTMENTS_PAA (DEPARTMENT_ID, DEPARTMENT_NAME, BLOCK_ID)
SELECT 50 AS DEPARTMENT_ID, 'Менеджмент' AS DEPARTMENT_NAME, 1 AS BLOCK_ID
FROM DUAL
 UNION
SELECT 60 AS DEPARTMENT_ID, 'Социология' AS DEPARTMENT_NAME, 1 AS BLOCK_ID
FROM DUAL
 UNION
 SELECT 70 AS DEPARTMENT_ID, 'История' AS DEPARTMENT_NAME, 2 AS BLOCK_ID
FROM DUAL
 UNION
 SELECT 80 AS DEPARTMENT_ID, 'Математика' AS DEPARTMENT_NAME, 2 AS BLOCK_ID
FROM DUAL
 UNION
 SELECT 90 AS DEPARTMENT_ID, 'Филология' AS DEPARTMENT_NAME, 3 AS BLOCK_ID
FROM DUAL
;

SELECT *
FROM HR.DEPARTMENTS_PAA;

COMMIT;
ROLLBACK;

