SELECT ROWID, ST.* 
FROM HR.STUDENTS_PAA ST;

DELETE FROM HR.STUDENTS_PAA ST
WHERE ST.ROWID IN 'AAASLYAAEAAAKoEAAL';

DELETE FROM HR.STUDENTS_PAA ST
WHERE ST.ROWID IN 'AAASLYAAEAAAKoEAAK';

DELETE FROM HR.STUDENTS_PAA ST
WHERE ST.ROWID IN 'AAASLYAAEAAAKoEAAM';




