SELECT ST.FULL_NAME, COUNT (ST.STUDENT_ID) AS DUALL
FROM HR.STUDENTS_PAA ST
GROUP BY ST.FULL_NAME
HAVING COUNT(ST.STUDENT_ID) >1;

Написать SQL запрос, который выводит строчки с дубликатами из таблицы STUDENTS_INICIALY.
