INSERT INTO HR.DEPARTMENTS_PAA (DEPARTMENT_ID, DEPARTMENT_NAME, BLOCK_ID)
SELECT 50 AS DEPARTMENT_ID, 'Ìåíåäæìåíò' AS DEPARTMENT_NAME, 1 AS BLOCK_ID
FROM DUAL
 UNION
SELECT 60 AS DEPARTMENT_ID, 'Ñîöèîëîãèÿ' AS DEPARTMENT_NAME, 1 AS BLOCK_ID
FROM DUAL
 UNION
 SELECT 70 AS DEPARTMENT_ID, 'Èñòîðèÿ' AS DEPARTMENT_NAME, 2 AS BLOCK_ID
FROM DUAL
 UNION
 SELECT 80 AS DEPARTMENT_ID, 'Ìàòåìàòèêà' AS DEPARTMENT_NAME, 2 AS BLOCK_ID
FROM DUAL
 UNION
 SELECT 90 AS DEPARTMENT_ID, 'Ôèëîëîãèÿ' AS DEPARTMENT_NAME, 3 AS BLOCK_ID
FROM DUAL
;

SELECT *
FROM HR.DEPARTMENTS_PAA;

COMMIT;
ROLLBACK;

