CREATE VIEW HR.STUDENTS_DEP_PAA AS
SELECT ST.STUDENT_ID, 
       DP.DEPARTMENT_NAME, 
       ST.TEACHER_ID, 
       ST.START_DATE, 
       ST.FULL_NAME, 
       ST.SCHOLARSHIP
FROM HR.STUDENTS_PAA ST
INNER JOIN HR.DEPARTMENTS_PAA DP
ON ST.DEPARTMENT_ID = DP.DEPARTMENT_ID
;
--Создать вьюшку на основе SQL, Название вью – STUDENTS_DEP_INICIALY
