SELECT *--EM.FIRST_NAME,LENGTH(EM.FIRST_NAME) AS MAX_LENGTH
FROM HR.EMPLOYEES EM
ORDER BY LENGTH(EM.FIRST_NAME) DESC
FETCH FIRST 1 ROWS ONLY;

--Получить список сотрудников с самым длинным именем (изучить функцию LENGTH)
