SELECT DP.DEPARTMENT_NAME
FROM HR.DEPARTMENTS_PAA DP
WHERE EXISTS (SELECT * FROM HR.STUDENTS_PAA ST
              WHERE ST.DEPARTMENT_ID=DP.DEPARTMENT_ID)
;

--Вывести названия департаментов, по которым есть студенты
